version: "3"

services:
  frontend:
    build: ./client
    ports:
      - "80:80"
    stdin_open: true
    volumes:
      - "./client:/usr/src/app"
      - "/usr/src/app/node_modules"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
  backend:
    build: ./server
    volumes:
      - "./server:/usr/src/app"
      - "/usr/src/app/node_modules"
    links:
      - mongo
    environment:
      - NODE_ENV=production
  mongo:
    hostname: mongo
    restart: always
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - "./docker/mongo/data:/data/db"
