version: "3"
services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - "./client:/usr/src/app"
    depends_on:
      - backend
  backend:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - "./server:/usr/src/app"
    links:
      - mongo
  mongo:
    hostname: mongo
    restart: always
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - "./docker/mongo/data:/data/db"
